* Remerciements
- Je remercie Dr. Michael Katz pour l'idée.
- Je remercie Dr. Adrian Baranchuk et ses collaborateurs de l'Université Queen de Kingston en Ontario au Canada pour le concept du « Brugadometer » et pour leur aide en appliquant cet algorithme.
- Je remercie Scott Kankkala pour l’idée des compas marchants.
- La traduction française est par David Mann, Gretchen Mann, Juliet Mann et Jean-Claude Hounou.  Je remercie Dr. Pierre Taboulet pour confirmer à moi que le compas d'un cardiologue est un "Compas" et pas "un Étrier!"
- Je remercie Victoria Churilina pour la traduction en russe.
- Le code source de *Compas EP* est disponible sur [[https://github.com/mannd/epcalipers-android][GitHub]].
- *Compas EP* est un logiciel libre et il est sous [[https://www.gnu.org/copyleft/gpl.html][GNU General Public License version 3]].  Nous ne fournissons aucune garantie sur la précision de l'application.  Utilisez-la à vos risques et périls.
- Pour des questions, des rapports d'erreurs, ou des suggestions, contactez mannd@epstudiossoftware.com.
- Le site Internet: https://www.epstudiossoftware.com.
